import type { AppState, Opportunity } from '../types'
import { addDays } from '../utils'

const now = new Date().toISOString()
const d = (offset: number) => addDays(now, offset)
const demoPasswords = {
  admin: import.meta.env.VITE_DEMO_ADMIN_PASSWORD ?? '',
  channelAdmin: import.meta.env.VITE_DEMO_CHANNEL_ADMIN_PASSWORD ?? '',
  salesAdmin: import.meta.env.VITE_DEMO_SALES_ADMIN_PASSWORD ?? '',
  sales: import.meta.env.VITE_DEMO_SALES_PASSWORD ?? '',
  channel: import.meta.env.VITE_DEMO_CHANNEL_PASSWORD ?? '',
  jdManager: import.meta.env.VITE_DEMO_JD_MANAGER_PASSWORD ?? '',
}

const accountOpportunitySpecs = [
  { id: 'opp_sales_ly_phone', customerName: '小米', companyName: '小米科技有限责任公司', industry: '3C / 数码', ownerId: 'u_ly', ownerName: '林悦', source: 'direct', stage: 'contacting', amountRange: '20to50', department: '手机市场部', requirement: '围绕小米手机新品用户洞察开展声访 AI 调研，已确认核心人群与首轮访谈范围。' },
  { id: 'opp_sales_ly_appliance', customerName: '海信', companyName: '海信集团控股股份有限公司', industry: '家电 / 智能硬件', ownerId: 'u_ly', ownerName: '林悦', source: 'direct', stage: 'proposal', amountRange: '20to50', department: '智慧家电事业部', requirement: '针对海信智慧家电购买决策链路开展声访 AI 调研，研究方案已提交客户评审。' },
  { id: 'opp_sales_ly_beauty', customerName: '欧莱雅', companyName: '欧莱雅（中国）有限公司', industry: '美妆 / 护肤', ownerId: 'u_ly', ownerName: '林悦', source: 'direct', stage: 'reporting', amountRange: '10to20', department: '消费者洞察部', requirement: '通过声访 AI 调研了解欧莱雅新品试用反馈与复购驱动因素，正在补充样本人群。' },
  { id: 'opp_sales_zn_phone', customerName: 'vivo', companyName: '维沃移动通信有限公司', industry: '3C / 数码', ownerId: 'u_zn', ownerName: '周宁', source: 'direct', stage: 'negotiation', amountRange: '20to50', department: '用户研究部', requirement: 'vivo 手机影像功能用户体验声访 AI 调研已完成需求确认，进入报价谈判阶段。' },
  { id: 'opp_sales_zn_appliance', customerName: '美的', companyName: '美的集团股份有限公司', industry: '家电 / 智能硬件', ownerId: 'u_zn', ownerName: '周宁', source: 'direct', stage: 'contacting', amountRange: '10to20', department: '用户体验中心', requirement: '围绕美的智能家居使用体验开展声访 AI 调研，已约定业务团队需求沟通会。' },
  { id: 'opp_sales_zn_beauty', customerName: '雅诗兰黛', companyName: '雅诗兰黛（上海）商贸有限公司', industry: '美妆 / 护肤', ownerId: 'u_zn', ownerName: '周宁', source: 'direct', stage: 'proposal', amountRange: '20to50', department: '品牌洞察部', requirement: '雅诗兰黛高端护肤消费动机声访 AI 调研已形成执行方案，等待客户确认排期。' },
  { id: 'opp_channel_xl_phone', customerName: 'OPPO', companyName: 'OPPO 广东移动通信有限公司', industry: '3C / 数码', ownerId: 'ch_xlsz', ownerName: '星链数字', source: 'channel', channelId: 'c_xlsz', channelName: '星链数字', stage: 'contacting', amountRange: '20to50', department: '用户洞察部', requirement: 'OPPO 手机换机需求声访 AI 调研由星链数字引荐，已完成研究目标与样本口径沟通。' },
  { id: 'opp_channel_xl_appliance', customerName: 'TCL', companyName: 'TCL 科技集团股份有限公司', industry: '家电 / 智能硬件', ownerId: 'ch_xlsz', ownerName: '星链数字', source: 'channel', channelId: 'c_xlsz', channelName: '星链数字', stage: 'reporting', amountRange: '10to20', department: '智能终端事业部', requirement: 'TCL 大屏产品家庭场景声访 AI 调研由星链数字报备，正在确认联系人和预算。' },
  { id: 'opp_channel_xl_beauty', customerName: '珀莱雅', companyName: '珀莱雅化妆品股份有限公司', industry: '美妆 / 护肤', ownerId: 'ch_xlsz', ownerName: '星链数字', source: 'channel', channelId: 'c_xlsz', channelName: '星链数字', stage: 'proposal', amountRange: '10to20', department: '市场研究部', requirement: '珀莱雅功效护肤人群声访 AI 调研已完成初步访谈框架，方案等待品牌方评审。' },
  { id: 'opp_channel_yq_phone', customerName: '一加', companyName: '深圳市万普拉斯科技有限公司', industry: '3C / 数码', ownerId: 'ch_yqkj', ownerName: '云启科技', source: 'channel', channelId: 'c_yqkj', channelName: '云启科技', stage: 'proposal', amountRange: '10to20', department: '产品策略部', requirement: '一加手机核心用户声访 AI 调研由云启科技引荐，研究框架与交付物已提交。' },
  { id: 'opp_channel_yq_appliance', customerName: '格力', companyName: '珠海格力电器股份有限公司', industry: '家电 / 智能硬件', ownerId: 'ch_yqkj', ownerName: '云启科技', source: 'channel', channelId: 'c_yqkj', channelName: '云启科技', stage: 'negotiation', amountRange: '20to50', department: '市场用户研究部', requirement: '格力空调焕新需求声访 AI 调研已确认样本规模，当前推进预算与执行周期审批。' },
  { id: 'opp_channel_yq_beauty', customerName: '花西子', companyName: '浙江宜格企业管理集团有限公司', industry: '美妆 / 护肤', ownerId: 'ch_yqkj', ownerName: '云启科技', source: 'channel', channelId: 'c_yqkj', channelName: '云启科技', stage: 'contacting', amountRange: '10to20', department: '消费者运营部', requirement: '花西子彩妆用户偏好声访 AI 调研由云启科技报备，正在确认重点品类与目标人群。' },
] as const

const newAccountOpportunities: Opportunity[] = accountOpportunitySpecs.map((item, index) => ({
  id: item.id,
  customerName: item.customerName,
  companyName: item.companyName,
  industry: item.industry,
  productInterests: ['JM 声访'],
  source: item.source,
  channelId: 'channelId' in item ? item.channelId : undefined,
  channelName: 'channelName' in item ? item.channelName : undefined,
  channelManagerName: item.source === 'channel' ? (item.channelId === 'c_xlsz' ? '潘子恒' : '马思源') : undefined,
  saOwnerId: item.ownerId,
  saOwnerName: item.ownerName,
  salesOwnerId: item.ownerId,
  salesOwnerName: item.ownerName,
  stage: item.stage,
  reportedAt: d(-12 - index),
  updatedAt: d(-Math.max(1, 6 - index % 5)),
  releaseAt: d(18 + index),
  lockedPermanently: false,
  contact: { level: index % 3 === 0 ? '决策层' : '执行层', department: item.department, contactTypes: index % 2 === 0 ? ['wechat', 'phone'] : ['email', 'phone'], encryptedName: `${item.customerName}业务负责人` },
  firstContactDate: d(-14 - index),
  requirementDescription: item.requirement,
  amountRange: item.amountRange,
  evidenceFiles: [{ id: `ef_${item.id}`, name: '声访调研需求沟通记录.jpg', url: '#', uploadedAt: d(-12 - index), uploadedBy: item.ownerId }],
  isFrozen: false,
  progressReports: [],
  renewalRequests: [],
}))

export const seedData: AppState = {
  currentUser: {
    id: 'admin1',
    name: '张管理',
    role: 'admin',
    email: 'admin@joymarketing.com',
  },

  users: [
    { id: 'admin1',    name: '张管理',  role: 'admin',         email: 'admin@joymarketing.com', password: demoPasswords.admin },
    { id: 'cadmin1',   name: '李渠道',  role: 'channel_admin', email: 'channeladmin@joymarketing.com', password: demoPasswords.channelAdmin },
    { id: 'sadmin1',   name: '王直客',  role: 'sales_admin',   email: 'salesadmin@joymarketing.com',   password: demoPasswords.salesAdmin },
    // 销售团队（默认密码 Joy@Sales2024）
    { id: 'u_yd',     name: '李天琦',  role: 'sales',   email: 'tianqi@joymarketing.com',       password: demoPasswords.sales },
    { id: 'u_cyz',    name: '陈耀忠',  role: 'sales',   email: 'chenyaozhong@joymarketing.com', password: demoPasswords.sales },
    { id: 'u_fzj',    name: '范泽瑾',  role: 'sales',   email: 'fanzejin@joymarketing.com',     password: demoPasswords.sales },
    { id: 'u_yj',     name: '俞佳',    role: 'sales',   email: 'yujia@joymarketing.com',        password: demoPasswords.sales },
    { id: 'u_pzh',    name: '潘子恒',  role: 'sales',   email: 'panziheng@joymarketing.com',    password: demoPasswords.sales },
    { id: 'u_msy',    name: '马思源',  role: 'sales',   email: 'masiyuan@joymarketing.com',     password: demoPasswords.sales },
    { id: 'u_zjy',    name: '周金月',  role: 'sales',   email: 'zhoujinyue@joymarketing.com',   password: demoPasswords.sales },
    { id: 'u_cr',     name: '曹睿',    role: 'sales',   email: 'caorui@joymarketing.com',       password: demoPasswords.sales },
    { id: 'u_cy',     name: '柴彦',    role: 'sales',   email: 'chaiyan@joymarketing.com',      password: demoPasswords.sales },
    { id: 'u_css',    name: '崔姗姗',  role: 'sales',   email: 'cuishanshan@joymarketing.com',  password: demoPasswords.sales },
    { id: 'u_zxp',    name: '张晓培',  role: 'sales',   email: 'zhangxiaopei@joymarketing.com', password: demoPasswords.sales },
    { id: 'u_ly',     name: '林悦',    role: 'sales',   email: 'linyue@joymarketing.com',        password: demoPasswords.sales, group: '智能终端组', createdAt: d(-7) },
    { id: 'u_zn',     name: '周宁',    role: 'sales',   email: 'zhouning@joymarketing.com',      password: demoPasswords.sales, group: '消费品牌组', createdAt: d(-6) },
    // 渠道账号（默认密码 Joy@Partner2024）
    { id: 'ch_xnkj',  name: '小能科技', role: 'channel', email: 'xnkj@partner.com', channelId: 'c_xnkj', password: demoPasswords.channel },
    { id: 'ch_kj',    name: '科技',     role: 'channel', email: 'kj@partner.com',    channelId: 'c_kj',   password: demoPasswords.channel },
    { id: 'ch_sykj',  name: '三亿科技', role: 'channel', email: 'sykj@partner.com', channelId: 'c_sykj', password: demoPasswords.channel },
    { id: 'ch_ykkj',  name: '驿氪科技', role: 'channel', email: 'ykkj@partner.com', channelId: 'c_ykkj', password: demoPasswords.channel },
    { id: 'ch_jxkj',  name: '佳翔科技', role: 'channel', email: 'jxkj@partner.com', channelId: 'c_jxkj', password: demoPasswords.channel },
    { id: 'ch_xlsz',  name: '星链数字', role: 'channel', email: 'xinglian@partner.com', channelId: 'c_xlsz', password: demoPasswords.channel, createdAt: d(-5) },
    { id: 'ch_yqkj',  name: '云启科技', role: 'channel', email: 'yunqi@partner.com', channelId: 'c_yqkj', password: demoPasswords.channel, createdAt: d(-4) },
    // 京东渠道经理账号（独立登录，默认密码 Jd@Manager2024）
    { id: 'jd_xnkj',  name: '周经理', role: 'channel', email: 'zhou.jd@joymarketing.com', channelId: 'c_xnkj', isJdManager: true, password: demoPasswords.jdManager },
    { id: 'jd_kj',    name: '吴经理', role: 'channel', email: 'wu.jd@joymarketing.com',   channelId: 'c_kj',   isJdManager: true, password: demoPasswords.jdManager },
    { id: 'jd_sykj',  name: '郑经理', role: 'channel', email: 'zheng.jd@joymarketing.com', channelId: 'c_sykj', isJdManager: true, password: demoPasswords.jdManager },
    { id: 'jd_ykkj',  name: '孙经理', role: 'channel', email: 'sun.jd@joymarketing.com',  channelId: 'c_ykkj', isJdManager: true, password: demoPasswords.jdManager },
    { id: 'jd_jxkj',  name: '冯经理', role: 'channel', email: 'feng.jd@joymarketing.com', channelId: 'c_jxkj', isJdManager: true, password: demoPasswords.jdManager },
  ],

  channels: [
    { id: 'c_xnkj', name: '小能科技', contactName: '小能负责人', email: 'xnkj@partner.com',  phone: '13900000001', status: 'active', createdAt: d(-90), jdManagerName: '周经理', jdManagerEmail: 'zhou.jd@joymarketing.com' },
    { id: 'c_kj',   name: '科技',     contactName: '科技负责人', email: 'kj@partner.com',     phone: '13900000002', status: 'active', createdAt: d(-80), jdManagerName: '吴经理', jdManagerEmail: 'wu.jd@joymarketing.com' },
    { id: 'c_sykj', name: '三亿科技', contactName: '三亿负责人', email: 'sykj@partner.com',  phone: '13900000003', status: 'active', createdAt: d(-75), jdManagerName: '郑经理', jdManagerEmail: 'zheng.jd@joymarketing.com' },
    { id: 'c_ykkj', name: '驿氪科技', contactName: '驿氪负责人', email: 'ykkj@partner.com',  phone: '13900000004', status: 'active', createdAt: d(-60), jdManagerName: '孙经理', jdManagerEmail: 'sun.jd@joymarketing.com' },
    { id: 'c_jxkj', name: '佳翔科技', contactName: '佳翔负责人', email: 'jxkj@partner.com',  phone: '13900000005', status: 'active', createdAt: d(-70), jdManagerName: '冯经理', jdManagerEmail: 'feng.jd@joymarketing.com' },
    { id: 'c_xlsz', name: '星链数字', fullName: '上海星链数字科技有限公司', contactName: '顾晨', email: 'xinglian@partner.com', phone: '13900000006', status: 'active', createdAt: d(-5), jdManagerName: '潘子恒' },
    { id: 'c_yqkj', name: '云启科技', fullName: '杭州云启智能科技有限公司', contactName: '宋雨', email: 'yunqi@partner.com', phone: '13900000007', status: 'active', createdAt: d(-4), jdManagerName: '马思源' },
  ],

  opportunities: [
    // 1. Joyinside — 内部客户 — 已签约
    {
      id: 'opp1',
      customerName: 'Joyinside',
      companyName: 'Joyinside',
      industry: '互联网 / 科技',
      source: 'direct',
      saOwnerId: 'u_yd', saOwnerName: '李天琦',
      salesOwnerId: 'u_yd', salesOwnerName: '李天琦',
      stage: 'signed',
      reportedAt: d(-90), updatedAt: d(-60), releaseAt: d(999),
      lockedPermanently: true,
      contact: { level: '决策层', department: 'Joyinside', contactTypes: ['wechat'], encryptedName: '内部对接人' },
      firstContactDate: d(-95),
      requirementDescription: '内部客户，Joyinside 产品线合作，年度框架协议已签署，持续推进中',
      amountRange: 'above50',
      evidenceFiles: [{ id: 'ef1', name: '内部合同.jpg', url: '#', uploadedAt: d(-90), uploadedBy: 'u_yd' }],
      contractNo: 'JI-2024-001', signedDate: d(-60), signedAmount: 120,
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 2. 荣耀 — 3C — 已签约
    {
      id: 'opp2',
      customerName: '荣耀',
      companyName: '荣耀终端有限公司',
      industry: '3C / 数码',
      source: 'direct',
      saOwnerId: 'u_cyz', saOwnerName: '陈耀忠',
      salesOwnerId: 'u_cyz', salesOwnerName: '陈耀忠',
      stage: 'signed',
      reportedAt: d(-80), updatedAt: d(-40), releaseAt: d(999),
      lockedPermanently: true,
      contact: { level: '决策层', department: 'CI+EC', contactTypes: ['phone', 'wechat'], encryptedName: '詹宏林' },
      firstContactDate: d(-85),
      requirementDescription: '荣耀 CI+EC 全域合作，覆盖品牌内容与电商运营两大业务线，已完成年度合同签署',
      amountRange: 'above50',
      evidenceFiles: [{ id: 'ef2', name: '合同签署.jpg', url: '#', uploadedAt: d(-80), uploadedBy: 'u_cyz' }],
      contractNo: 'RY-2024-001', signedDate: d(-40), signedAmount: 380,
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 3. 博士西门子 — 家电 — 签约中
    {
      id: 'opp3',
      customerName: '博士西门子',
      companyName: '博西家用电器有限公司',
      industry: '家电 / 智能硬件',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'signing',
      reportedAt: d(-30), updatedAt: d(-7), releaseAt: d(15),
      lockedPermanently: false,
      contact: { level: '决策层', department: 'CI', contactTypes: ['phone', 'email'], encryptedName: '何雪莹' },
      firstContactDate: d(-35),
      requirementDescription: '博士西门子 CI 内容营销项目，覆盖品牌形象升级与内容制作，合同条款已对齐，等待客户法务审核',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef3', name: '洽谈截图.jpg', url: '#', uploadedAt: d(-30), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 4. 脉动 — 食品饮料 — 初接触
    {
      id: 'opp4',
      customerName: '脉动',
      companyName: '达能（中国）食品饮料有限公司',
      industry: '食品 / 饮料',
      source: 'direct',
      saOwnerId: 'u_cyz', saOwnerName: '陈耀忠',
      salesOwnerId: 'u_cyz', salesOwnerName: '陈耀忠',
      stage: 'reporting',
      reportedAt: d(-15), updatedAt: d(-5), releaseAt: d(15),
      lockedPermanently: false,
      contact: { level: '执行层', department: 'EC', contactTypes: ['wechat'], encryptedName: '王泽芳' },
      firstContactDate: d(-18),
      requirementDescription: '脉动电商运营项目初步接触，客户对 JD 电商代运营方案有兴趣，已完成首次需求沟通',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef4', name: '微信沟通记录.jpg', url: '#', uploadedAt: d(-15), uploadedBy: 'u_cyz' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 5. 疯狂小狗 — 宠物 — 初接触
    {
      id: 'opp5',
      customerName: '疯狂小狗',
      companyName: '疯狂小狗宠物用品有限公司',
      industry: '宠物',
      source: 'direct',
      saOwnerId: 'u_yj', saOwnerName: '俞佳',
      salesOwnerId: 'u_yj', salesOwnerName: '俞佳',
      stage: 'reporting',
      reportedAt: d(-12), updatedAt: d(-4), releaseAt: d(18),
      lockedPermanently: false,
      contact: { level: '执行层', department: '营销', contactTypes: ['wechat', 'phone'], encryptedName: '刘金鹏' },
      firstContactDate: d(-14),
      requirementDescription: '疯狂小狗宠物品牌营销合作初步接触，对品牌内容与社交媒体推广有明确预算，进入方案对接阶段',
      amountRange: '5to10',
      evidenceFiles: [{ id: 'ef5', name: '拜访照片.jpg', url: '#', uploadedAt: d(-12), uploadedBy: 'u_yj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 6. 海尔 — 家电 — 渠道(小能科技) — 项目交付
    {
      id: 'opp6',
      customerName: '海尔',
      companyName: '海尔集团公司',
      industry: '家电 / 智能硬件',
      source: 'channel',
      channelId: 'c_xnkj', channelName: '小能科技',
      channelManagerName: '潘子恒',
      saOwnerId: 'ch_xnkj', saOwnerName: '小能科技',
      salesOwnerId: 'ch_xnkj', salesOwnerName: '小能科技',
      stage: 'delivery',
      reportedAt: d(-100), updatedAt: d(-10), releaseAt: d(999),
      lockedPermanently: true,
      contact: { level: '决策层', department: 'EC', contactTypes: ['phone', 'email'], encryptedName: '海尔EC负责人' },
      firstContactDate: d(-105),
      requirementDescription: '海尔电商代运营项目，覆盖全品类店铺运营与营销推广，合同已签署，当前进入交付执行阶段',
      amountRange: 'above50',
      evidenceFiles: [{ id: 'ef6', name: '合同.jpg', url: '#', uploadedAt: d(-100), uploadedBy: 'ch_xnkj' }],
      contractNo: 'HL-2024-001', signedDate: d(-70), signedAmount: 520,
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 7. 安利 — 快消 — 初接触
    {
      id: 'opp7',
      customerName: '安利',
      companyName: '安利（中国）日用品有限公司',
      industry: '食品 / 饮料',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'reporting',
      reportedAt: d(-20), updatedAt: d(-6), releaseAt: d(10),
      lockedPermanently: false,
      contact: { level: '决策层', department: '用户体验', contactTypes: ['phone'], encryptedName: '安利对接人' },
      firstContactDate: d(-22),
      requirementDescription: '安利用户体验优化项目，聚焦线上用户体验与内容运营，客户已表达合作意向，方案制作中',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef7', name: '需求文档截图.jpg', url: '#', uploadedAt: d(-20), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 8. 雀巢 — 快消 — 签约中
    {
      id: 'opp8',
      customerName: '雀巢',
      companyName: '雀巢（中国）有限公司',
      industry: '食品 / 饮料',
      source: 'direct',
      saOwnerId: 'u_cyz', saOwnerName: '陈耀忠',
      salesOwnerId: 'u_cyz', salesOwnerName: '陈耀忠',
      stage: 'signing',
      reportedAt: d(-40), updatedAt: d(-8), releaseAt: d(18),
      lockedPermanently: false,
      contact: { level: '决策层', department: 'EC', contactTypes: ['phone', 'wechat'], encryptedName: '武爱丽' },
      firstContactDate: d(-45),
      requirementDescription: '雀巢电商全域运营合作，覆盖天猫京东双平台，合同已进入法务阶段，预计本月内签署',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef8', name: '方案确认邮件.jpg', url: '#', uploadedAt: d(-40), uploadedBy: 'u_cyz' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 10. 宝洁（SKII）— 美妆 — 已签约
    {
      id: 'opp10',
      customerName: '宝洁（SKII）',
      companyName: '宝洁（中国）销售有限公司',
      industry: '美妆 / 护肤',
      source: 'direct',
      saOwnerId: 'u_msy', saOwnerName: '马思源',
      salesOwnerId: 'u_msy', salesOwnerName: '马思源',
      stage: 'signed',
      reportedAt: d(-70), updatedAt: d(-35), releaseAt: d(999),
      lockedPermanently: true,
      contact: { level: '决策层', department: 'CI', contactTypes: ['phone', 'wechat'], encryptedName: '詹宏林' },
      firstContactDate: d(-75),
      requirementDescription: 'SKII 品牌内容营销合作，覆盖全年内容策划与创意制作，年度合同已签署',
      amountRange: 'above50',
      evidenceFiles: [{ id: 'ef10', name: '签约合同.jpg', url: '#', uploadedAt: d(-70), uploadedBy: 'u_msy' }],
      contractNo: 'SKII-2024-001', signedDate: d(-35), signedAmount: 280,
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 11. 三星 — 3C — 渠道(科技) — 签约中
    {
      id: 'opp11',
      customerName: '三星',
      companyName: '三星（中国）投资有限公司',
      industry: '3C / 数码',
      source: 'channel',
      channelId: 'c_kj', channelName: '科技',
      channelManagerName: '潘子恒',
      saOwnerId: 'ch_kj', saOwnerName: '科技',
      salesOwnerId: 'u_yd', salesOwnerName: '李天琦',
      stage: 'signing',
      reportedAt: d(-35), updatedAt: d(-9), releaseAt: d(20),
      lockedPermanently: false,
      contact: { level: '决策层', department: 'TP+CI', contactTypes: ['phone', 'email'], encryptedName: '三星对接人' },
      firstContactDate: d(-38),
      requirementDescription: '三星 TP+CI 整合营销合作，覆盖技术支持与品牌内容双线，当前方案对齐完成，合同起草中',
      amountRange: 'above50',
      evidenceFiles: [{ id: 'ef11', name: '沟通记录.jpg', url: '#', uploadedAt: d(-35), uploadedBy: 'ch_kj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 12. 五粮液 — 酒水 — 初接触
    {
      id: 'opp12',
      customerName: '五粮液',
      companyName: '四川省宜宾五粮液股份有限公司',
      industry: '酒水',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'reporting',
      reportedAt: d(-22), updatedAt: d(-7), releaseAt: d(8),
      lockedPermanently: false,
      contact: { level: '决策层', department: '品牌部', contactTypes: ['phone', 'wechat'], encryptedName: '卞天恩' },
      firstContactDate: d(-25),
      requirementDescription: '五粮液品牌营销合作，聚焦品牌升级与年度内容规划，已完成首次高层拜访，等待客户内部立项',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef12', name: '拜访记录.jpg', url: '#', uploadedAt: d(-22), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 13. 舍得 — 酒水 — 渠道(三亿科技) — 初接触
    {
      id: 'opp13',
      customerName: '舍得',
      companyName: '舍得酒业股份有限公司',
      industry: '酒水',
      source: 'channel',
      channelId: 'c_sykj', channelName: '三亿科技',
      channelManagerName: '周金月',
      saOwnerId: 'ch_sykj', saOwnerName: '三亿科技',
      salesOwnerId: 'ch_sykj', salesOwnerName: '三亿科技',
      stage: 'reporting',
      reportedAt: d(-14), updatedAt: d(-3), releaseAt: d(16),
      lockedPermanently: false,
      contact: { level: '执行层', department: 'EC', contactTypes: ['wechat'], encryptedName: '舍得EC负责人' },
      firstContactDate: d(-16),
      requirementDescription: '舍得电商运营项目初步接触，通过三亿科技渠道引入，客户有明确电商提升需求，方案沟通中',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef13', name: '初步沟通截图.jpg', url: '#', uploadedAt: d(-14), uploadedBy: 'ch_sykj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 京东大药房 — 大健康 — 签约中
    {
      id: 'opp25',
      customerName: '京东大药房',
      companyName: '京东大药房（青岛）连锁有限公司',
      industry: '大健康 / 医疗',
      source: 'direct',
      saOwnerId: 'u_yd', saOwnerName: '李天琦',
      salesOwnerId: 'u_yd', salesOwnerName: '李天琦',
      stage: 'signing',
      reportedAt: d(-18), updatedAt: d(-1), releaseAt: d(12),
      lockedPermanently: false,
      contact: { level: '决策层', department: '用户运营', contactTypes: ['phone', 'wechat'], encryptedName: '健康业务负责人' },
      firstContactDate: d(-21),
      requirementDescription: '京东大药房会员增长与健康服务体验优化项目，已完成方案沟通并进入商务谈判',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef25', name: '方案确认邮件.jpg', url: '#', uploadedAt: d(-3), uploadedBy: 'u_yd' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 14. 艾芙尼 — 快消 — 渠道(驿氪科技) — 初接触
    {
      id: 'opp14',
      customerName: '艾芙尼',
      companyName: '艾芙尼（上海）化妆品有限公司',
      industry: '食品 / 饮料',
      source: 'channel',
      channelId: 'c_ykkj', channelName: '驿氪科技',
      channelManagerName: '曹睿',
      saOwnerId: 'ch_ykkj', saOwnerName: '驿氪科技',
      salesOwnerId: 'ch_ykkj', salesOwnerName: '驿氪科技',
      stage: 'reporting',
      reportedAt: d(-10), updatedAt: d(-2), releaseAt: d(20),
      lockedPermanently: false,
      contact: { level: '执行层', department: '营销', contactTypes: ['wechat', 'phone'], encryptedName: '艾芙尼营销负责人' },
      firstContactDate: d(-12),
      requirementDescription: '艾芙尼营销数字化合作，由驿氪科技渠道引入，聚焦会员运营与营销自动化，需求调研中',
      amountRange: '5to10',
      evidenceFiles: [{ id: 'ef14', name: '需求调研.jpg', url: '#', uploadedAt: d(-10), uploadedBy: 'ch_ykkj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 15. 东风汽车（卓联）— 汽车 — 初接触
    {
      id: 'opp15',
      customerName: '东风汽车（卓联）',
      companyName: '东风汽车集团有限公司',
      industry: '汽车 / 出行',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'reporting',
      reportedAt: d(-17), updatedAt: d(-4), releaseAt: d(13),
      lockedPermanently: false,
      contact: { level: '执行层', department: '用户体验', contactTypes: ['phone', 'email'], encryptedName: '王卫东' },
      firstContactDate: d(-20),
      requirementDescription: '东风汽车卓联用户体验项目，覆盖用户旅程优化与数字化触点建设，客户已提供需求文档，方案制作中',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef15', name: '需求文档.jpg', url: '#', uploadedAt: d(-17), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 16. 人头马 — 酒水 — 初接触
    {
      id: 'opp16',
      customerName: '人头马',
      companyName: '人头马君度（上海）酒业有限公司',
      industry: '酒水',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'reporting',
      reportedAt: d(-8), updatedAt: d(-2), releaseAt: d(22),
      lockedPermanently: false,
      contact: { level: '执行层', department: '营销', contactTypes: ['wechat'], encryptedName: '卞天恩' },
      firstContactDate: d(-10),
      requirementDescription: '人头马品牌营销合作初步接触，客户有高端烈酒品牌推广需求，已完成初次品牌简报对齐',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef16', name: '品牌简报.jpg', url: '#', uploadedAt: d(-8), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 17. 嘉士伯 — 酒水 — 初接触
    {
      id: 'opp17',
      customerName: '嘉士伯',
      companyName: '嘉士伯啤酒（广东）有限公司',
      industry: '酒水',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'reporting',
      reportedAt: d(-11), updatedAt: d(-3), releaseAt: d(19),
      lockedPermanently: false,
      contact: { level: '执行层', department: '营销', contactTypes: ['phone', 'wechat'], encryptedName: '卞天恩' },
      firstContactDate: d(-13),
      requirementDescription: '嘉士伯啤酒营销合作项目，聚焦夏季促销与品牌内容，客户已确认预算范围，方案对齐中',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef17', name: '初次洽谈截图.jpg', url: '#', uploadedAt: d(-11), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 18. 蒙牛 — 快消 — 签约中
    {
      id: 'opp18',
      customerName: '蒙牛',
      companyName: '内蒙古蒙牛乳业（集团）股份有限公司',
      industry: '食品 / 饮料',
      source: 'direct',
      saOwnerId: 'u_cyz', saOwnerName: '陈耀忠',
      salesOwnerId: 'u_cyz', salesOwnerName: '陈耀忠',
      stage: 'signing',
      reportedAt: d(-45), updatedAt: d(-10), releaseAt: d(12),
      lockedPermanently: false,
      contact: { level: '决策层', department: 'CI', contactTypes: ['phone', 'email'], encryptedName: '蒙牛品牌总监' },
      firstContactDate: d(-50),
      requirementDescription: '蒙牛品牌内容营销合作，覆盖品牌 CI 升级与年度内容规划，合同条款已基本确认，等待客户最终审批',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef18', name: '合同草案确认.jpg', url: '#', uploadedAt: d(-45), uploadedBy: 'u_cyz' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 19. 康明斯 — 工业/制造 — 初接触
    {
      id: 'opp19',
      customerName: '康明斯',
      companyName: '康明斯（中国）投资有限公司',
      industry: '工业 / 制造',
      source: 'direct',
      saOwnerId: 'u_cy', saOwnerName: '柴彦',
      salesOwnerId: 'u_cy', salesOwnerName: '柴彦',
      stage: 'reporting',
      reportedAt: d(-16), updatedAt: d(-5), releaseAt: d(14),
      lockedPermanently: false,
      contact: { level: '执行层', department: '市场部', contactTypes: ['email', 'phone'], encryptedName: '康明斯市场负责人' },
      firstContactDate: d(-18),
      requirementDescription: '康明斯工业品牌数字营销项目，客户希望提升 B2B 品牌影响力与线上询盘转化，需求对齐中',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef19', name: '邮件往来截图.jpg', url: '#', uploadedAt: d(-16), uploadedBy: 'u_cy' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 20. 创维电视 — 家电 — 渠道(佳翔科技) — 已签约
    {
      id: 'opp20',
      customerName: '创维电视',
      companyName: '创维集团有限公司',
      industry: '家电 / 智能硬件',
      source: 'channel',
      channelId: 'c_jxkj', channelName: '佳翔科技',
      channelManagerName: '崔姗姗',
      saOwnerId: 'ch_jxkj', saOwnerName: '佳翔科技',
      salesOwnerId: 'ch_jxkj', salesOwnerName: '佳翔科技',
      stage: 'signed',
      reportedAt: d(-75), updatedAt: d(-30), releaseAt: d(999),
      lockedPermanently: true,
      contact: { level: '决策层', department: '客服部', contactTypes: ['phone', 'wechat'], encryptedName: '创维客服总监' },
      firstContactDate: d(-80),
      requirementDescription: '创维电视客服数字化升级项目，通过佳翔科技渠道引入，客服系统与 AI 赋能合同已签署',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef20', name: '签约合同.jpg', url: '#', uploadedAt: d(-75), uploadedBy: 'ch_jxkj' }],
      contractNo: 'CW-2024-001', signedDate: d(-30), signedAmount: 160,
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 21. 华为 — 3C — 项目交付
    {
      id: 'opp21',
      customerName: '华为',
      companyName: '华为技术有限公司',
      industry: '3C / 数码',
      source: 'direct',
      saOwnerId: 'u_zxp', saOwnerName: '张晓培',
      salesOwnerId: 'u_zxp', salesOwnerName: '张晓培',
      stage: 'delivery',
      reportedAt: d(-110), updatedAt: d(-5), releaseAt: d(999),
      lockedPermanently: true,
      contact: { level: '决策层', department: 'CI', contactTypes: ['phone', 'wechat', 'email'], encryptedName: '陈荣康' },
      firstContactDate: d(-115),
      requirementDescription: '华为 CI 品牌内容年度合作，覆盖全品类产品线内容制作与投放，合同已签署，当前进入全面交付阶段',
      amountRange: 'above50',
      evidenceFiles: [{ id: 'ef21', name: '框架合同.jpg', url: '#', uploadedAt: d(-110), uploadedBy: 'u_zxp' }],
      contractNo: 'HW-2024-002', signedDate: d(-80), signedAmount: 450,
      isFrozen: false, progressReports: [], renewalRequests: [],
    },

    // 22. 元气森林 — 食品饮料 — 初接触
    {
      id: 'opp22',
      customerName: '元气森林',
      companyName: '元气森林（北京）食品科技集团有限公司',
      industry: '食品 / 饮料',
      source: 'direct',
      saOwnerId: 'u_fzj', saOwnerName: '范泽瑾',
      salesOwnerId: 'u_fzj', salesOwnerName: '范泽瑾',
      stage: 'reporting',
      reportedAt: d(-9), updatedAt: d(-2), releaseAt: d(21),
      lockedPermanently: false,
      contact: { level: '执行层', department: '市场部', contactTypes: ['wechat', 'phone'], encryptedName: '卞天恩' },
      firstContactDate: d(-11),
      requirementDescription: '元气森林年度营销合作初步接触，客户有全渠道内容与电商运营提升需求，已完成初步需求沟通',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef22', name: '初次沟通记录.jpg', url: '#', uploadedAt: d(-9), uploadedBy: 'u_fzj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },
    // 23. 农夫山泉 — 食品饮料 — 即将到期释放（剩 3 天）
    {
      id: 'opp23',
      customerName: '农夫山泉',
      companyName: '农夫山泉股份有限公司',
      industry: '食品 / 饮料',
      source: 'direct',
      saOwnerId: 'u_yj', saOwnerName: '俞佳',
      salesOwnerId: 'u_yj', salesOwnerName: '俞佳',
      stage: 'reporting',
      reportedAt: d(-27), updatedAt: d(-10), releaseAt: d(3),
      lockedPermanently: false,
      contact: { level: '执行层', department: '市场部', contactTypes: ['phone', 'email'], encryptedName: '农夫山泉对接人' },
      firstContactDate: d(-28),
      requirementDescription: '农夫山泉新品上市内容营销合作，已完成初步需求沟通，但近两周进展停滞，保护期临近',
      amountRange: '20to50',
      evidenceFiles: [{ id: 'ef23', name: '需求沟通纪要.jpg', url: '#', uploadedAt: d(-27), uploadedBy: 'u_yj' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },
    // 24. 蕉下 — 服装时尚 — 即将到期释放（剩 6 天）
    {
      id: 'opp24',
      customerName: '蕉下',
      companyName: '深圳减字科技有限公司',
      industry: '服装 / 时尚',
      source: 'direct',
      saOwnerId: 'u_msy', saOwnerName: '马思源',
      salesOwnerId: 'u_msy', salesOwnerName: '马思源',
      stage: 'reporting',
      reportedAt: d(-24), updatedAt: d(-8), releaseAt: d(6),
      lockedPermanently: false,
      contact: { level: '决策层', department: '品牌部', contactTypes: ['wechat', 'phone'], encryptedName: '蕉下品牌负责人' },
      firstContactDate: d(-25),
      requirementDescription: '蕉下夏季防晒系列品牌种草合作，已对接品牌负责人，方案待客户内部评审，保护期即将到期',
      amountRange: '10to20',
      evidenceFiles: [{ id: 'ef24', name: '合作方案沟通.jpg', url: '#', uploadedAt: d(-24), uploadedBy: 'u_msy' }],
      isFrozen: false, progressReports: [], renewalRequests: [],
    },
    ...newAccountOpportunities,
  ],

  logs: [],
  notifications: [
    {
      id: 'ntf1', userId: 'admin1',
      title: '渠道商机举证待审核',
      body: '「海尔」由小能科技报备，沟通截图已提交，请尽快审核举证材料。',
      type: 'warning', read: false, createdAt: d(-1), opportunityId: 'opp6',
    },
    {
      id: 'ntf2', userId: 'admin1',
      title: '大额商机进入签约阶段',
      body: '「雀巢」已推进至签约中，预估金额较高，建议重点跟进合同进展。',
      type: 'info', read: false, createdAt: d(-2), opportunityId: 'opp8',
    },
    {
      id: 'ntf3', userId: 'admin1',
      title: '商机长时间未更新进展',
      body: '「三星」自报备以来超过 7 天未提交进展更新，请提醒负责人跟进。',
      type: 'warning', read: false, createdAt: d(-3), opportunityId: 'opp11',
    },
    {
      id: 'ntf4', userId: 'admin1',
      title: '新商机成功报备',
      body: '「元气森林」已由范泽瑾完成报备，已进入 30 天保护期。',
      type: 'success', read: false, createdAt: d(-1), opportunityId: 'opp22',
    },
  ],
}
